// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMyPIN():Promise<string>;

export function SelectFile():Promise<string>;

export function SendFile(arg1:string,arg2:string,arg3:string):Promise<string>;
