// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuditLog() {
  return window['go']['main']['App']['GetAuditLog']();
}

export function GetFingerprint() {
  return window['go']['main']['App']['GetFingerprint']();
}

export function GetMyPIN() {
  return window['go']['main']['App']['GetMyPIN']();
}

export function ProtocolInfo() {
  return window['go']['main']['App']['ProtocolInfo']();
}

export function RespondToOffer(arg1, arg2) {
  return window['go']['main']['App']['RespondToOffer'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendFile'](arg1, arg2, arg3, arg4, arg5);
}
