// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMyPIN() {
  return window['go']['main']['App']['GetMyPIN']();
}

export function ProtocolInfo() {
  return window['go']['main']['App']['ProtocolInfo']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFile'](arg1, arg2, arg3);
}
