// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuditLog(): Promise<string>;

export function GetFingerprint(): Promise<string>;

export function GetMyPIN(): Promise<string>;

export function ProtocolInfo(): Promise<string>;

export function RespondToOffer(arg1: string, arg2: boolean): Promise<string>;

export function SelectFile(): Promise<string>;

export function SendFile(
  arg1: string,
  arg2: string,
  arg3: string,
  arg4: string,
  arg5: string,
): Promise<string>;
